export interface WarehouseDelivery {
  id: string;
  transactionNumber: string;
  userType: 'owned' | 'consignment';
  productId: string;
  productName: string;
  siteId: string;
  siteName: string;
  tankId: string;
  tankName: string;
  amount: number;
  unit: 'kg' | 'ton';
  deliveryDate: Date;
  status: 'draft' | 'saved' | 'issued' | 'finalized' | 'printed' | 'correction_requested';
  notes?: string;
  companyId?: string;
  companyName?: string;
  companyAddress?: string;
  companyPhone?: string;
  companyContactPerson?: string;
  companyRegistrationNumber?: string;
  contractId?: string;
  contractNumber?: string;
  locationId?: string;
  locationName?: string;
  locationAddress?: string;
  locationPhone?: string;
  locationPostalCode?: string;
  internalSiteId?: string;
  internalSiteName?: string;
  contractorSiteId?: string;
  contractorSiteName?: string;
  driverId?: string;
  driverName?: string;
  driverNationalId?: string;
  driverPlateNumber?: string;
  driverHomeAddress?: string;
  recipientType?: 'company' | 'customer';
  customerCompanyId?: string;
  customerCompanyName?: string;
  customerLocationId?: string;
  customerLocationName?: string;
  companyLocationId?: string;
  companyLocationName?: string;
  fromPermit?: boolean;
  permitId?: string;
  systemPermitNumber?: string;
  permitNumber?: string;
  managementLetterNumber?: string;
  permitAmount?: number;
  wastageAmount?: number;
  finalPermitAmount?: number;
  receiptId?: string;
  receiptNumber?: string;
  permitDate?: string;
  approvalDate?: string;
  trustDelivery?: boolean;
  receiptBasisAmount?: number;
  remainingTransferPermit?: number;
  createdAt: Date;
  updatedAt: Date;
  shipName?: string;
  quotaNumber?: string;
  registrationOrderNumber?: string;
  isVoided?: boolean;
  counterpartyName?: string;
  slipDate?: Date;
  event?: string;
  _editingSource?: 'parent' | 'transaction-list';
  _isParentEdit?: boolean;
  _isNewFromPermit?: boolean;
  editMode?: string;
  remainingPermitAmount?: number;
  additionalInfo?: {
    driverFirstName?: string;
    driverLastName?: string;
    driverNationalId?: string;
    billOfLadingNumber?: string;
    plateNumber?: string;
    weight?: number;
    billAmount?: number;
    destination?: string;
    billDate?: Date;
    transportCompany?: string;
    driverMobile?: string;
    destinationAddress?: string;
    backBillAmount?: number;
    destinationPostalCode?: string;
  };
}

export interface DeliveryFilters {
  userType?: string;
  status?: string;
  dateFrom?: Date;
  dateTo?: Date;
}